title: "Karthik ch"
email: karthhikchapalamadugu@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my portfolio website!
baseurl: "/" 
url: "https://karthikchapalamadugu.github.io/" 
twitter_username: Karthik Chapalamadugu
github_username:  karthikchapalamadugu

sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg
